name: g2s_profiles
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - numpy
  - pandas
  - matplotlib
  - ipython
  - pip
  - pip:
      - -e .
      - git+https://github.com/chetzer-ncpa/ncpag2s-clc.git